### ISSUE TITLE
lights in upstairs hall closet won't turn off

### ISSUE THREAD

**Issue by bengoodger** [bengoodger/ranchtastic#123]
closet door switch is flaky?

**Comment by delcontejeff** [comment]
Still trying to figure it out. We came up with a conclusion, hopefully implement tomorrow

**Comment by bengoodger** [comment]
if you did, seems like it didn't quite work.

**Comment by delcontejeff** [comment]
No show ( surprise) electricians yesterday

**Comment by delcontejeff** [comment]
And we can make adjustments to grades, slopes, etc. also asked Klope to chime in on grade at bottom of west stairs, pool deck, pool wall grade transition.

**Comment by delcontejeff** [comment]
painter to finish touch ups
