### ISSUE TITLE
chimney cap looks bent

### ISSUE THREAD

**Issue by bengoodger** [bengoodger/ranchtastic#127]
looking at the house from the front, the front face of the chimney cap looks like it has deflected in with the latest winds. also the center support clip for it is leaned back.

can we correct the deflection and reinforce it so that it does not occur again.

**Comment by delcontejeff** [comment]
They came out today, measured for support pieces for added strength to alleviate the thunder in your house and stop future deflects.

**Comment by bengoodger** [comment]
was this work done? it looks un-bent

**Comment by delcontejeff** [comment]
They still have to add the “stabilizers” for high winds. Measured and should be out this week to install.

**Comment by bengoodger** [comment]
was this completed?

**Comment by delcontejeff** [comment]
The need to come back and stiffen the west panel, all other sides have been completed. Don’t know if it was windy enough for you to notice a difference in sound transference into your home?

**Comment by delcontejeff** [comment]
They said they’d be back tomorrow to finish

From: Jeff Del Conte [mailto:jeff@rjdailey.com] 
Sent: Monday, March 02, 2015 10:12 AM
To: 'bengoodger/ranchtastic'
Subject: RE: [ranchtastic] chimney cap looks bent (#127)

The need to come back and stiffen the west panel, all other sides have been completed. Don’t know if it was windy enough for you to notice a difference in sound transference into your home?
