### ISSUE TITLE
hot water slow upstairs

### ISSUE THREAD

**Issue by bengoodger** [bengoodger/ranchtastic#129]
did they not turn on the recirc pump? it takes 2-3 mins to get hot water now @ the master

**Comment by delcontejeff** [comment]
Hi,

They didn’t replace the water heater, right before install we notice it had a huge dent.  It was under the blue plastic cap so it was not noticeable. They will be back Monday with another unit, they are not the plumbers we hired but the water heater’s tech/warranty replacement team.

Can I come by in a while and see about the recirc pump? Probably not on or plugged in.

**Comment by bengoodger** [comment]
It was not plugged in. I plugged it back in to the outlet right above. Can probably close this.
