### ISSUE TITLE
Fireplace stone hearth trim piece

### ISSUE THREAD

**Issue by bengoodger** [bengoodger/ranchtastic#13]
In both dining room and great room, as discussed, stone trim piece @ floor to obscure hardwood end & metal trim piece on the fireplace appliance.

**Comment by delcontejeff** [comment]
Good News, informed this am that they do have enough material for dining room side, fabricating today and will be here tomorrow to install both side

**Comment by bengoodger** [comment]
Cool!

**Comment by delcontejeff** [comment]
installed
