### ISSUE TITLE
switch cover at outdoor bbq for lighting impossible to open

### ISSUE THREAD

**Issue by bengoodger** [bengoodger/ranchtastic#134]
not the heater switches, the switch for the lights over the counter. unable to turn off lights now. also one of the bulbs is burned out.

**Comment by delcontejeff** [comment]
Hi Ben,

There is a small black tab, where you want to break the cover apart on the bottom, that you can press and it allows the cover to open.

And again took me a few minutes to figure out, after final we can lose the covers.

I can show you later today if you’d like.
