### ISSUE TITLE
Door fell off blue star

### ISSUE THREAD

**Issue by bengoodger** [bengoodger/ranchtastic#137]
Smaller oven. Right hinge detached.

**Comment by bengoodger** [comment]
Jeff Marissa asks if this is something you can fix.

**Comment by delcontejeff** [comment]
Yes

My guys Everado and Aaron can do this right now, they are still there.

If that’s OK

**Comment by delcontejeff** [comment]
They may have dust masks there also, if that’s better

**Comment by bengoodger** [comment]
fixed thanks
