### ISSUE TITLE
Drawer hardware installed at incorrect locations at dining room china cabinet

### ISSUE THREAD

**Issue by bengoodger** [bengoodger/ranchtastic#15]
Drawer drop pulls are installed with the centerline @ the drop pull mount, rather than the center of the total drop pull height as discussed and shown on masking tape. It is OK to try and patch this but if the patch is visible the affected drawer fronts will have to be replaced.

**Comment by delcontejeff** [comment]
installed at correct location, painter to touch up
Jan wanted to look at lower 2 handles, though they might be OK as is.
