### ISSUE TITLE
breakers that lanai heaters are on keep tripping

### ISSUE THREAD

**Issue by bengoodger** [bengoodger/ranchtastic#155]
pretty much every time I use the heaters the next time they won't work and when I look I find the breakers flipped. need to be upgraded??

**Comment by delcontejeff** [comment]
Hi Ben,

Tom will be out either Thursday or Friday, he suspects the breaker needs replacing.

I’ll keep you posted as I get the info.

**Comment by bengoodger** [comment]
Jeff these are still tripping. In fact I can't even get them on anymore. This can be dealt with this week. Please make sure this is fixed properly this time.

**Comment by delcontejeff** [comment]
Tom reviewed yesterday, will replace the timer switch and install a temporary switch until new timer arrives.

Should also be hooking up the disposal in the bbq.

**Comment by bengoodger** [comment]
Jeff did Tom change the switches on these? The timers that were on there were up to 6hrs of continuous use. Now they are up to 60min of continuous use. Probably won't use them for 6hrs but need more than 60mins.

**Comment by delcontejeff** [comment]
Hi

Yes he did, he will order timers with longer duration is 3-4 hours OK?
