### ISSUE TITLE
exposed concrete/mesh wire by north side of pool cover

### ISSUE THREAD

**Issue by bengoodger** [bengoodger/ranchtastic#160]
stay outside of pool safety fence. approach the pool near where the cover enclosure is and look at the mulch. see exposed chicken wire/concrete/partially inside the pool enclosure. surely this could be treated a bit better?

**Comment by delcontejeff** [comment]
Hi

I will come by and take a look at both items

**Comment by delcontejeff** [comment]
Apologies for that oversight, Paradise will be out to take care of that.
