### ISSUE TITLE
bedrooms are excessively cold with ac on

### ISSUE THREAD

**Issue by bengoodger** [bengoodger/ranchtastic#164]
with doors closed, air isn't circulating into the hallway to thermostat
no airflow/registers etc. in hallway

**Comment by bengoodger** [comment]
as discussed jeff will ask about hvac design

**Comment by delcontejeff** [comment]
Hi Ben,

Spoke to Mike of DG HVAC, he suggested adding a supply in hallway near laundry room in the ceiling to fix this issue. Do you want this done a.s.a.p. or wait until 7/13?

**Comment by bengoodger** [comment]
can wait until after 7/13

**Comment by delcontejeff** [comment]
10-4

**Comment by delcontejeff** [comment]
Hi Ben,

We can schedule this for Monday PM, afternoon. 

They will be up in the upstairs attic and in the hall  near the laundry.

We should verify the location of the supply prior to commencement.

LMK,

Thanks,

Jeff
