### ISSUE TITLE
Order T-strikes

### ISSUE THREAD

**Issue by bengoodger** [bengoodger/ranchtastic#2]
Waiting on https://www.handlesets.com/index.cfm?page=ecrm:order&ordernumber=61743696&h=79C186F0856448C30E7C582174254759E73731D851B3DC5212D8590C7810603D

**Comment by delcontejeff** [comment]
jeff will pick up today, please cancel order

**Comment by delcontejeff** [comment]
order cancelled, picked up t-strikes
