### ISSUE TITLE
master deck rail/stairs

### ISSUE THREAD

**Issue by bengoodger** [bengoodger/ranchtastic#51]

**Comment by delcontejeff** [comment]
ETA week of 12/15

**Comment by delcontejeff** [comment]
UPDATE FROM YESTERDAY:
due to Holidays stair wnt be shipped until first week in december

**Comment by bengoodger** [comment]
do you mean first week in january? it's the third week in december already :-)

**Comment by delcontejeff** [comment]
Yes that’s what I meant to say.
