### ISSUE TITLE
Flush electrical panel in garage into wall. 

### ISSUE THREAD

**Issue by bengoodger** [bengoodger/ranchtastic#53]
Currently it appears to be surface mounted on the sheetrock.

**Comment by delcontejeff** [comment]
generator panel due week of 15th

**Comment by bengoodger** [comment]
so this is done though the sheetrock above doesn't go behind it perfectly...

**Comment by bengoodger** [comment]
don't suppose there's a chance they could tidy up the sheetrock a bit there.

**Comment by delcontejeff** [comment]
Yes we can and will
