### ISSUE TITLE
Wifi is poor in great room.

### ISSUE THREAD

**Issue by bengoodger** [bengoodger/ranchtastic#56]
Ben/Icon.

Looks like the AP in the media cabinet was moved to the master. I think we need an additional AP.

**Comment by delcontejeff** [comment]
Ben, Ryan of Icon tested between 45 -50 mbs at about 1230 pm

**Comment by bengoodger** [comment]
Still seeing poor reception @ couch in great room. There used to be an AP in the media cabinet, did it get moved?

**Comment by delcontejeff** [comment]
ICON should send email explaining situation

**Comment by bengoodger** [comment]
seems ok now
