### ISSUE TITLE
Slide range back 1"

### ISSUE THREAD

**Issue by bengoodger** [bengoodger/ranchtastic#59]
Jeff states gas supply line needs to be modified so that the range can be slid back entirely into the slab/cabinet opening for it.

**Comment by delcontejeff** [comment]
tomorrow am scheduled. we will be pulling the oven out of cabinet 8:00 am

**Comment by delcontejeff** [comment]
only meant to comment

**Comment by delcontejeff** [comment]
slid range back 1" , need countertop sub  to reinstall new piece to tighten gap behind

**Comment by delcontejeff** [comment]
stainless steel trim installed
