### ISSUE TITLE
Attach fridge door panels

### ISSUE THREAD

**Issue by bengoodger** [bengoodger/ranchtastic#7]
Blocked on #6 .

**Comment by delcontejeff** [comment]
slight adjustments needed

**Comment by delcontejeff** [comment]
appliance installers scheduled Tuesday can make final adjustments, as well as install wine cooler door

**Comment by delcontejeff** [comment]
sorry Thursday for installers

**Comment by delcontejeff** [comment]
thursday 12/18 for service tech to adjust fridge door lower left corner

**Comment by delcontejeff** [comment]
rescheduled 12/22

**Comment by bengoodger** [comment]
looks pretty good
