### ISSUE TITLE
Set screw needed in Liam's door lever, inside

### ISSUE THREAD

**Issue by bengoodger** [bengoodger/ranchtastic#77]
Door lever works its way loose, looks like set screw is missing.

**Comment by bengoodger** [comment]
also inside master bedroom door

**Comment by delcontejeff** [comment]
tightened down both as well as garage

**Comment by bengoodger** [comment]
nope, still loose.

**Comment by bengoodger** [comment]
(in liam's room, on the inside)

**Comment by bengoodger** [comment]
also storage room outside lever

**Comment by delcontejeff** [comment]
hi want to close, but next step would be to" loc tite" all set screws.

**Comment by delcontejeff** [comment]
retightened. close?
