### ISSUE TITLE
rain shower drips occasionally while hand shower is on

### ISSUE THREAD

**Issue by bengoodger** [bengoodger/ranchtastic#80]

**Comment by delcontejeff** [comment]
Hi Ben, that is common with rain showers, they will drip for a while after the water is turned off.

**Comment by bengoodger** [comment]
It also drips while the hand held head is on.

**Comment by bengoodger** [comment]
I'm going to keep an eye on this. I logged this because I noticed it dripping noisily > 30min after use which seemed weird. I'll update if I see this condition repeat.
