### ISSUE TITLE
missing crystal chain on master bedroom chandelier

### ISSUE THREAD

**Issue by bengoodger** [bengoodger/ranchtastic#86]
if you look at it from the entry door you'll see there's a gap where there should be a chain and there's only  one crystal segment.

**Comment by delcontejeff** [comment]
Currey & Company    Watteau 9161    Silver Granello
is this the correct fixture? and where do you purchase from?

**Comment by bengoodger** [comment]
so the box/parts are gone? if so i can look into the part.

**Comment by delcontejeff** [comment]
yes please

**Comment by bengoodger** [comment]
Update: Currey & Co. is going to send us another.
