### ISSUE TITLE
range hood only works when kitchen lights are on

### ISSUE THREAD

**Issue by bengoodger** [bengoodger/ranchtastic#89]

**Comment by delcontejeff** [comment]
Hi

That’s the only way it works until we get the correct switch installed.

**Comment by bengoodger** [comment]
yeah but in that case would the hood light only work if the kitchen lights were on?

**Comment by delcontejeff** [comment]
no hood lights are separate from all other lights

**Comment by bengoodger** [comment]
jeff any update here? it's been an awfully long time...

**Comment by delcontejeff** [comment]
Have the part, will get icon to install next week.
