### ISSUE TITLE
Rangehood relay needs repair

### ISSUE THREAD

**Issue by bengoodger** [bengoodger/ranchtastic#9]
Currently the lights in the range hood are wired together with the fan because the fan relay is broken according to the electrician. This relay needs repair so the fan can be controlled separately from the lights.

**Comment by bengoodger** [comment]
Jeff states hood needs to be replaced with model with inline blower switch.

**Comment by delcontejeff** [comment]
new info - we are more than likely able to replace switch to control in line fan

**Comment by delcontejeff** [comment]
switch and bracket have been ordered

**Comment by bengoodger** [comment]
same... when is this getting fixed????
